//! Remote Cross-Chain Hub (CCH) JSON-RPC client.
//!
//! Fiber Studio acts as a CCH *client*: it calls a hub operator's RPC to create
//! swap orders, then uses the local Fiber node to pay or receive the Fiber leg.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use super::rpc::{CkbScript, JsonRpcError, RpcResponse};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "PascalCase")]
pub enum CchOrderStatus {
    Pending,
    IncomingAccepted,
    OutgoingInFlight,
    OutgoingSuccess,
    Success,
    Failed,
}

impl CchOrderStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "Pending",
            Self::IncomingAccepted => "IncomingAccepted",
            Self::OutgoingInFlight => "OutgoingInFlight",
            Self::OutgoingSuccess => "OutgoingSuccess",
            Self::Success => "Success",
            Self::Failed => "Failed",
        }
    }

    pub fn is_final(&self) -> bool {
        matches!(self, Self::Success | Self::Failed)
    }
}

/// Proxy invoice generated by the hub for the incoming payment leg.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum CchInvoice {
    Fiber(String),
    Lightning(String),
}

impl CchInvoice {
    #[allow(dead_code)]
    pub fn as_fiber(&self) -> Option<&str> {
        match self {
            Self::Fiber(value) => Some(value.as_str()),
            Self::Lightning(_) => None,
        }
    }

    #[allow(dead_code)]
    pub fn as_lightning(&self) -> Option<&str> {
        match self {
            Self::Lightning(value) => Some(value.as_str()),
            Self::Fiber(_) => None,
        }
    }

    pub fn encoded(&self) -> &str {
        match self {
            Self::Fiber(value) | Self::Lightning(value) => value.as_str(),
        }
    }

    pub fn kind_label(&self) -> &'static str {
        match self {
            Self::Fiber(_) => "Fiber",
            Self::Lightning(_) => "Lightning",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CchOrder {
    /// Seconds since epoch (hex-encoded over the wire).
    #[serde(alias = "created_at")]
    pub timestamp: String,
    pub expiry_delta_seconds: String,
    pub wrapped_btc_type_script: CkbScript,
    pub incoming_invoice: CchInvoice,
    pub outgoing_pay_req: String,
    pub payment_hash: String,
    pub amount_sats: String,
    pub fee_sats: String,
    pub status: CchOrderStatus,
    #[serde(default)]
    pub failure_reason: Option<String>,
}

#[derive(Debug, Error)]
pub enum CchError {
    #[error("{0}")]
    Message(String),
    #[error("Could not reach the CCH hub RPC: {0}")]
    Request(#[from] reqwest::Error),
    #[error("{0}")]
    Rpc(#[from] JsonRpcError),
    #[error("CCH hub RPC response was empty")]
    MissingResult,
}

pub fn normalize_rpc_url(url: &str) -> Result<String, CchError> {
    let trimmed = url.trim().trim_end_matches('/');
    if trimmed.is_empty() {
        return Err(CchError::Message(
            "CCH hub RPC URL is not configured. Set it in Settings.".into(),
        ));
    }

    let lower = trimmed.to_ascii_lowercase();
    if !(lower.starts_with("http://") || lower.starts_with("https://")) {
        return Err(CchError::Message(
            "CCH hub RPC URL must start with http:// or https://.".into(),
        ));
    }

    Ok(trimmed.to_string())
}

/// True when `invoice` looks like a BOLT11 Lightning payment request.
pub fn looks_like_bolt11(invoice: &str) -> bool {
    let trimmed = invoice.trim().to_ascii_lowercase();
    trimmed.starts_with("lnbc")
        || trimmed.starts_with("lntb")
        || trimmed.starts_with("lnbcrt")
        || trimmed.starts_with("lnsb")
}

async fn call_cch_rpc<T: serde::de::DeserializeOwned>(
    rpc_url: &str,
    method: &str,
    params: serde_json::Value,
) -> Result<T, CchError> {
    let url = normalize_rpc_url(rpc_url)?;
    let client = reqwest::Client::new();
    let body = serde_json::json!({
        "jsonrpc": "2.0",
        "method": method,
        "params": params,
        "id": 1
    });

    let response = client.post(url).json(&body).send().await?;
    let payload: RpcResponse<T> = response.json().await?;

    if let Some(error) = payload.error {
        return Err(CchError::Rpc(error));
    }

    payload.result.ok_or(CchError::MissingResult)
}

pub async fn send_btc(
    rpc_url: &str,
    btc_pay_req: &str,
    currency: &str,
) -> Result<CchOrder, CchError> {
    let invoice = btc_pay_req.trim();
    if invoice.is_empty() {
        return Err(CchError::Message("Lightning invoice is required.".into()));
    }
    if !looks_like_bolt11(invoice) {
        return Err(CchError::Message(
            "Expected a Lightning BOLT11 invoice (lnbc… / lntb…).".into(),
        ));
    }

    call_cch_rpc(
        rpc_url,
        "send_btc",
        serde_json::json!([{
            "btc_pay_req": invoice,
            "currency": currency,
        }]),
    )
    .await
}

pub async fn receive_btc(rpc_url: &str, fiber_pay_req: &str) -> Result<CchOrder, CchError> {
    let invoice = fiber_pay_req.trim();
    if invoice.is_empty() {
        return Err(CchError::Message("Fiber invoice is required.".into()));
    }

    call_cch_rpc(
        rpc_url,
        "receive_btc",
        serde_json::json!([{
            "fiber_pay_req": invoice,
        }]),
    )
    .await
}

pub async fn get_cch_order(rpc_url: &str, payment_hash: &str) -> Result<CchOrder, CchError> {
    let hash = payment_hash.trim();
    if hash.is_empty() {
        return Err(CchError::Message("Payment hash is required.".into()));
    }

    let normalized = if hash.starts_with("0x") || hash.starts_with("0X") {
        hash.to_string()
    } else {
        format!("0x{hash}")
    };

    call_cch_rpc(
        rpc_url,
        "get_cch_order",
        serde_json::json!([{
            "payment_hash": normalized,
        }]),
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_bolt11_prefixes() {
        assert!(looks_like_bolt11("lnbc100u1p…"));
        assert!(looks_like_bolt11("LNTB1…"));
        assert!(looks_like_bolt11("  lnbcrt1…  "));
        assert!(!looks_like_bolt11("fibt1000000001p…"));
        assert!(!looks_like_bolt11(""));
    }

    #[test]
    fn normalize_rpc_url_rejects_empty_and_non_http() {
        assert!(normalize_rpc_url("").is_err());
        assert!(normalize_rpc_url("ws://127.0.0.1:8227").is_err());
        assert_eq!(
            normalize_rpc_url("https://cch.example/rpc/").unwrap(),
            "https://cch.example/rpc"
        );
    }

    #[test]
    fn deserializes_fiber_incoming_invoice() {
        let json = r#"{
            "timestamp": "0x661f",
            "expiry_delta_seconds": "0x1f980",
            "wrapped_btc_type_script": {
                "code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
                "hash_type": "type",
                "args": "0x9a1086531ed6dc69e0bd44cef5278e03faf3015b31aff60b08fb87663ce8507100000000"
            },
            "incoming_invoice": { "Fiber": "fibt1abc" },
            "outgoing_pay_req": "lntb1xyz",
            "payment_hash": "0xabcd",
            "amount_sats": "0x2710",
            "fee_sats": "0x1",
            "status": "Pending"
        }"#;

        let order: CchOrder = serde_json::from_str(json).unwrap();
        assert_eq!(order.incoming_invoice.as_fiber(), Some("fibt1abc"));
        assert_eq!(order.status, CchOrderStatus::Pending);
        assert_eq!(order.amount_sats, "0x2710");
    }
}
