pub mod amounts;
pub mod bootnodes;
pub mod channel;
pub mod ckb_address;
pub mod ckb_indexer;
pub mod config_read;
pub mod data_directory;
pub mod invoices;
pub mod invoice_display;
pub mod config;
pub mod keychain;
pub mod log_store;
pub mod logs;
pub mod manager;
pub mod payment_display;
pub mod peer_connect;
pub mod process;
pub mod provision;
pub mod relays;
pub mod rpc;
pub mod sent_payments;
pub mod spawn;
pub mod studio;

pub const FNN_VERSION: &str = "0.9.0-rc7";
